logitの対数尤度を計算する関数の実装
komatsuna4747/gitpractice pull request #3
Opened 2021-07-21 04:54 UTC by komatsuna4747

Close #2.

# Sample code
```r
# Set seed
set.seed(1)

# Number of observations
N <- 1000

# Outcome binary variable
y <- sample(x = c(0, 1), size = N, replace = TRUE)

# Covariates
X <- matrix(rnorm(2 * N), ncol = 2)

# Parameters
beta <- c(1, -1)

# Check the function
compute_logit_lnlikelihood(beta, y, X)
```

2021-07-29 06:38 UTC, justinian336 requested changes
Pull Requestをありがとうございました！
コメントで指摘した件に加えて、この関数の単体テストを追加していただけると助かります 🙇🏼 。
関数が正しく動くかを確認するテストと、引数が正しくない場合（例えば、`y`と`X`の次元が合わない、関数に渡されるパレメーターの数が`X`の次元に合わない、など）、適切なエラーが出力されるかを確認するテストがあればいいなと思います。

2021-07-29 06:38 UTC, justinian336 commented on R/compute_logit_lnlikelihood.R
> +compute_logit_lnlikelihood <- function (param, y, X) {
Documentationが不足していると思います。
この関数は何をするものか、`param`, `y`や`X`はそれぞれどのタイプの引数（vector, matrix, etc.）なのか、関数はなにを返すかをroxygenコメントで説明を加えてください。
R Studioでは簡単に加えることができます：https://stackoverflow.com/a/30675146

2021-07-29 06:38 UTC, justinian336 commented on R/compute_logit_lnlikelihood.R
> +  for (i in 1:length(y)) {
こんな時はループよりベクトル化を使ったほうがいいです。なぜなら、Rは裏で行列演算を最適化するためこの関数で行われてる処理は、特にデータが大きい場合、とても速くなる。ループはそのような最適化が行われないのでパフォーマンス的にはあまり望ましくないです。

2021-07-29 06:38 UTC, justinian336 commented on R/compute_logit_lnlikelihood.R
> +      exp_xb <- exp_xb + X[i, k] * param[[k]]
この計算では`X`が定数項が含まれていると想定されているがどこでもチェックされていない。チェックするコードを加えたほうがいい気がしますがいかがでしょうか。

2021-07-30 02:58 UTC, komatsuna4747 commented on R/compute_logit_lnlikelihood.R
> +compute_logit_lnlikelihood <- function (param, y, X) {
a092e31 で対応しました。roxygenだけでなく、関数の本体の方にもコメントを加えてあります。

2021-07-30 03:02 UTC, komatsuna4747 commented on R/compute_logit_lnlikelihood.R
> +  for (i in 1:length(y)) {
- 行列演算を用いたコードへの修正は d07f482 で対応しました。
- 対数尤度が正しく計算されていることを確認する単体テストは ce7e885 で作成しました。

単体テストを作成しているときに気づきましたが、もともとの関数の実装も間違ってましたね。正しく書くなら以下の通りです。
```r
for (k in 1:ncol(X)) {
  xb <- xb + X[i, k] * beta[[k]]
}
exp_xb <- exp(xb)
```

2021-07-30 03:07 UTC, komatsuna4747 commented on R/compute_logit_lnlikelihood.R
> +      exp_xb <- exp_xb + X[i, k] * param[[k]]
悩みましたが、以下のように定数項とそれ以外を別々に引数として取るように修正しました。定数項をinputに入れないとエラーが発生します。

Xのパラメーター (param_covariate) と X の column の数が一致しないときエラーを出すかの確認は ce7e885 で作成したテストで含めています。 

https://github.com/komatsuna4747/gitpractice/blob/a092e31427ebef9f9743169463cf19f593ae0706/R/compute_logit_lnlikelihood.R#L11

2023-09-27 04:20 UTC, closed without merging